- CHANGELOG.md
- package.json
- plugin.xml
- src/android/PurchasesPlugin.java
- src/ios/CDVPurchasesPlugin.m
Fixes . https://github.com/RevenueCat/cordova-plugin-purchases/issues/15
> Fixes regression introduced on Android purchase errors

- package.json
Should fix https://github.com/RevenueCat/cordova-plugin-purchases/issues/41
> link ts types

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Bug Report template:
There are certain project specific issues that are commonly misinterpreted as bugs.
- [Offerings, products, or available packages are empty](https://support.revenuecat.com/hc/en-us/articles/360041793174)
- [Invalid Play Store credentials errors](https://support.revenuecat.com/hc/en-us/articles/360046398913)
- [Unable to connect to the App Store (STORE_PROBLEM) errors](https://support.revenuecat.com/hc/en-us/articles/360046399333)
For support I'd recommend our [online community](https://spectrum.chat/revenuecat), [StackOverflow](https://stackoverflow.com/tags/revenuecat/) and/or [Help Center](https://support.revenuecat.com/hc/en-us) 👍
If you have a clearly defined bug (with a [Minimal, Complete, and Reproducible …
> Adds issue templates

- src/android/PurchasesPlugin.java
We were using a lambda, which are only compatible with certain versions of the JDK and Android. I removed it since someone reported having issues with it. We should just rewrite the plugin in Kotlin at some point
> Removes lambda

- src/plugin/plugin.ts
- www/plugin.d.ts
- www/plugin.js
just realized I'd forgot to open this, but it's a similar (albeit smaller) version of what was done in https://github.com/RevenueCat/react-native-purchases/pull/231
> cleaned up return types for sync methods

- src/plugin/plugin.ts
Thank you for contributing to Purchases. Before pressing the "Create Pull Request" button, please provide the following:
I believe the type for availablePackages was meant to be an array of PurchasesPackages, however the syntax was wrong.
https://github.com/RevenueCat/cordova-plugin-purchases/issues/93
No unit tests added for this type change.
> Update Type for avaiablePackages

- www/plugin.d.ts
Followup on https://github.com/RevenueCat/cordova-plugin-purchases/pull/94/files
> Run build to fix type after fixing availablePackages type

- package-lock.json
- plugin.xml
- src/android/PurchasesPlugin.java
- src/ios/CDVPurchasesPlugin.h
- src/ios/CDVPurchasesPlugin.m
- src/plugin/plugin.ts
- tests/plugin.test.ts
- www/plugin.d.ts
- www/plugin.js
> Add canMakePayments method

- src/plugin/plugin.ts
- www/plugin.d.ts
- www/plugin.js
Add void return type and remove incorrect doc
> Fix return type in canMakePayments documentation

- examples/cordova-sample/MyApp/package-lock.json
- examples/cordova-sample/MyApp/package.json
- plugin.xml
- src/android/PurchasesPlugin.java
- src/ios/CDVPurchasesPlugin.m
- src/plugin/plugin.ts
- www/plugin.d.ts
- www/plugin.js
adds: 
- `logIn`
- `logOut`
deprecates: 
- `allowSharingStoreAccount`
- `identify`
- `createAlias`
- `reset`
> Feature: identity v3

- CHANGELOG.md
> fix bad link in changelog

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
We were still pointing to Spectrum in the issues and the CONTRIBUTING.md
> Updates old spectrum links

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/issuecomplete.yml
- .github/stale.yml
Made the changes to the bot configuration to remove references to the legacy Help Center, adds some additional support links, and decreases the amount of time before an issue is closed.
> bot updates

- examples/cordova-sample/MyApp/bin/sk_config_setup.rb
The config file was added to the scheme, but that wasn't enough to get it on device, we needed to also add it to the project.
> Add StoreKit config file to xcproj

- plugin.xml
- src/android/PurchasesPlugin.java
resolves [CSDK-303]
[CSDK-303]: https://revenuecats.atlassian.net/browse/CSDK-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Android: Adopt purchases-hybrid-common:3.2.0

- examples/cordova-sample/MyApp/bin/sk_config_setup.rb
Resolves [CSDK-271]
[CSDK-271]: https://revenuecats.atlassian.net/browse/CSDK-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> iOS: Add "Refresh js resources" build phase run script

- examples/cordova-sample/MyApp/bin/sk_config_setup.rb
- src/ios/PurchasesPlugin.swift
The script needed to be updated to handle situations where the Swift version didn't get set.
Setting version to 5 showed that there were still a couple more updates needed for the Swift file.
> Update project setup script and Swift to 5.0

- plugin.xml
> Bump PHC to 3.2.2

- README.md
> `README`: fixed minimum Xcode / iOS version

- .circleci/config.yml
- RELEASING.md
- fastlane/Fastfile
- package.json
- scripts/docs/index.html
- tsconfig.json
Fixes [CSDK-325]
[CSDK-325]: https://revenuecats.atlassian.net/browse/CSDK-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Documentation generation

- .circleci/config.yml
- apiTester/attributes.ts
- apiTester/customerInfo.ts
- apiTester/enums.ts
- apiTester/offerings.ts
- apiTester/purchases.ts
- apiTester/tsconfig.json
Adds api tester.
CI configure as well.
Resolves [CSDK-142]
[CSDK-142]: https://revenuecats.atlassian.net/browse/CSDK-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add APITester

- examples/cordova-sample/MyApp/bin/sk_config_setup.rb
A late change introduced a small bug when setting swift_version.
> Set swift version to number, not true.

- .circleci/config.yml
Fix for https://app.circleci.com/pipelines/github/RevenueCat/cordova-plugin-purchases/744/workflows/d97bd476-188f-4e71-a0a8-e7360b6fbb00/jobs/1256
> Increase timeout for pod command

- examples/cordova-sample/MyApp/www/css/index.css
- examples/cordova-sample/MyApp/www/index.html
- examples/cordova-sample/MyApp/www/js/index.js
Absolutely embarrassing web code, but this adds actual buttons to purchaseTester in cordova.
> Improve purchase tester

- .circleci/config.yml
- fastlane/Fastfile
- fastlane/README.md
- Added release trains
- Added manual triggers
- Added workflow to be triggered remotely when updating purchases-hybrid-common
> Configures release train

- .circleci/config.yml
- RELEASING.md
Update releasing docs to match the release train changes
> Update releasing docs

- apiTester/offerings.ts
- src/plugin/plugin.ts
- www/plugin.d.ts
[CSDK-592](https://revenuecats.atlassian.net/browse/CSDK-592)
[CSDK-592]: https://revenuecats.atlassian.net/browse/CSDK-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adds PurchasesStoreProduct.subscriptionPeriod

- .circleci/config.yml
Fix for broken tests in https://github.com/RevenueCat/cordova-plugin-purchases/pull/282
> Fix Android integration tests

- .editorconfig
- src/android/PurchasesPlugin.java
- src/plugin/plugin.ts
Added a `.editorconfig` file and formatted using the correct settings
> Formats files correctly

- src/plugin/plugin.ts
I noticed `canMakePayments` docs were incorrect
> Fix `canMakePayments` jsdoc

- apiTester/enums.ts
- apiTester/purchases.ts
- apiTester/tsconfig.json
- examples/cordova-sample/MyApp/www/index.html
- examples/cordova-sample/MyApp/www/js/index.js
- src/android/PurchasesPlugin.java
- src/ios/PurchasesPlugin+APIHelpers.swift
- src/ios/PurchasesPlugin+Purchasing.swift
- src/plugin/plugin.ts
- tests/plugin.test.ts
Added:
- `Purchases.beginRefundRequestForActiveEntitlement`
-  `Purchases.beginRefundRequestForEntitlement`
-  `Purchases.beginRefundRequestForProduct`
> Adds beginRefund functions

- apiTester/enums.ts
- src/plugin/plugin.ts
added `immediateAndChargeFullPrice` proration mode
> add `immediateAndChargeFullPrice` proration mode

- apiTester/enums.ts
- src/plugin/plugin.ts
Refer to https://github.com/RevenueCat/purchases-android/pull/1209 for more information
> Temporarily remode DEFERRED proration mode in preparation for upgrade to Billing Client 6

- apiTester/enums.ts
- apiTester/purchases.ts
- examples/cordova-sample/MyApp/www/index.html
- examples/cordova-sample/MyApp/www/js/index.js
- src/android/PurchasesPlugin.java
- src/ios/PurchasesPlugin+Purchasing.swift
- src/ios/PurchasesPlugin.swift
- src/plugin/plugin.ts
- tests/plugin.test.ts
Adds in-app message APIs that allow to control whether the messages are shown automatically or defer them to a moment of choice
> Add in app message apis

- README.md
- src/plugin/plugin.ts
Found these issues when updating the awesome-cordova-plugins plugin and figured we should fix them
> Fix some docs

- src/android/PurchasesPlugin.java
- src/ios/PurchasesPlugin+Purchasing.swift
This fixes support for PHC after bumping to v10
> Support new PHC purchase methods

- README.md
We have this in the docs but I thought it would be good to add it to this repo's README as well.
> Add deprecation note in README

- .circleci/config.yml
- plugin.xml
Adds deployment target to plugin so ios integration tests pass.
> Fix ios integration tests

- README.md
This updates the expiration date after we released the new major.
> Update SDK expiration date

- CHANGELOG.md
> Add warning with 7.x issues to all versions since 7.0.0 in CHANGELOG
