RevenueCat/cordova-plugin-purchases

README.md

Forcing the code example to address the type parameter in makePurchase rather than rely on defaults.  I get that it's cleaner the other way, but I missed this the first time around and lost a day on it.
Also added missing "=>" in example code

Update makePurchase example in readme

---

.circleci/config.yml
.npmignore
jest.config.js
package-lock.json
package.json
plugin.xml
src/android/PurchasesPlugin.java
src/ios/CDVPurchasesPlugin.h
src/ios/CDVPurchasesPlugin.m
src/plugin/plugin.ts
tests/plugin.test.ts
tsconfig.json
tslint.json
www/plugin.d.ts
www/plugin.js
yarn.lock

This PR: 
- Adds TypeScript and does a basic refactor of `plugin.js` to TypeScript.
- Add a script to compile down to ES5
- Adds jest and ts-jest, and a basic test of `.setup`. Test coverage should be completed in subsequent PRs
- Removes ESLint in favor of TSLint
- Adds the project to CI and run the tests, lint and build
- Also commits the transpiled .js file, since upon looking at some TypeScript Cordova plugin projects, this is what folks prefer doing.

compile javascript down to ES5, test environment and CI

---

README.md

This API was updated to just take a string of the old SKU instead of an array, this PR just updates the README example to use the new API.

Update makePurchase example to use updated API.

---

src/plugin/plugin.ts

We forgot to export the TypeScript types so that people can use them in their TypeScript projects. I also made some fixes in some JSDocs blocks.

Fixes some JSdocs and exports types

---

CHANGELOG.md
package.json
plugin.xml

Adds a bump for version 1.0.5, which includes the changes in https://github.com/RevenueCat/cordova-plugin-purchases/pull/25 and https://github.com/RevenueCat/cordova-plugin-purchases/pull/26

[final] bump: version 1.0.5

---

src/plugin/plugin.ts
www/plugin.d.ts
www/plugin.js

Invalidating the cache is simultaneously an advanced technique and attractive to beginners who might think they need to invalidate the cache on every app launch, so I added a link to our docs that explains how to work with the cache in normal circumstances.
This will update plugin.js, plugin.ts, plugin.d.ts.
See RevenueCat/purchases-ios#223

Update invalidatePurchaserInfoCache docs

---

plugin.xml

I noticed this line in the terminal while running:
```
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
```
So I updated the plugin.xml file to use the new format for pods. 
I tried removing the ios platform, adding it again and running and it works as expected.
As usual, you can override the generated Podfile if you want to point to development versions of the plugin.

replaced deprecated framework tag with podspec tag

---

src/plugin/plugin.ts
www/plugin.d.ts
www/plugin.js

Updates the docs for the new attribution subscriber attributes methods to match the more descriptive ones found in other hybrid SDKs. 
I missed this when opening https://github.com/RevenueCat/cordova-plugin-purchases/pull/56.

Update docs to match other hybrid SDKs

---

src/android/PurchasesPlugin.java

Should fix this https://github.com/RevenueCat/cordova-plugin-purchases/issues/58
Looking at the code of the plugin we use to remove boilerplate in the Android plugin class:
https://github.com/appfeel/cordova-annotated-plugin-android/blob/master/src/android/CordovaPluginAction.java#L66
```
if (executionThread == ExecutionThread.WORKER) {
cordova.getThreadPool().execute(runnable);
} else if (executionThread == ExecutionThread.UI) {
cordova.getActivity().runOnUiThread(runnable);
} else {
runnable.run();
}
```
Passing `ExecutionThread.MAIN` just runs in the thread that the method is executed on. I changed all the ones that were called in `ExecutionThread.MAIN` to `ExecutionThread.UI` to make sure they care called in the UI thread. 
I think this error …

Changes ExecutionThread from MAIN to UI in Android

---

examples/cordova-sample/MyApp/config.xml
examples/cordova-sample/MyApp/package-lock.json
examples/cordova-sample/MyApp/package.json

With `"cordova-android": "^9.0.0"` there is a new preference `AndroidXEnabled` that enables AndroidX. I also added the `cordova-plugin-add-swift-support` plugin because I was getting the `error: Value for SWIFT_VERSION cannot be empty.` error when building the project

Enable androidx and swift support plugin in example

---

.circleci/config.yml
package.json
scripts/install-android-tools.sh
tests/package.json
tests/plugin.xml
tests/tests.js

- Adds two job to CircleCI
- android-integration-test: runs a simple test on an emulator to verify the SDK can be configured, an appUserID is assigned and purchaserInfo can be fetched
- ios-integration-test: same as the Android test but on an iOS simulator
- The api key is passed via an env variable configured in CircleCI.
- The UpsellScreen in the example now takes care of fetching offerings itself and this is not done when loading the App anymore.
- We use cordova-paramedic for the tests, which will basically create a new project and add our plugin. It runs our tests on that project afterwards

Integration tests

---

.circleci/config.yml

I believe the problem is that the cache was created in another working directory, or machine or something like that, and the restore is failing. I have invalidated the cache by updating the key to v2

Patch 2.0.0 to fix tests

---

.gitignore
jest.config.js
package-lock.json
package.json

Security update since we got a warning from GitHub about outdated dependencies. 
Mostly a straightforward update, but I did have to update `jest` a bit, and update the `testEnvironment` for it to work.
Tests do execute as expected, though.

Security update

---

src/plugin/plugin.ts

Inspired by https://github.com/RevenueCat/purchases-flutter/issues/361
The comment for entitlement's `willRenew` was wrong. Lifteime purchases will return `false`

Update willRenew comment - will be false for lifetime

---

examples/cordova-sample/MyApp/README.md
examples/cordova-sample/MyApp/bin/refresh_javascript_sources_ios.sh
examples/cordova-sample/MyApp/package.json
package.json
www/plugin.d.ts

Dependency broke us: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60310
Upgrade to newer TypeScript anyway since we're in the process of bringing this plugin up to the most recent RevenueCat SDK releases.

Dependency broke us, update TypeScript

---

.gitignore
Gemfile.lock
examples/cordova-sample/MyApp/www/js/index.js
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin.swift
src/plugin/plugin.ts
tests/tests.js
www/plugin.d.ts
www/plugin.js

`invalidatePurchaserInfoCache -> invalidateCustomerInfoCache`
`getPurchaserInfo -> getCustomerInfo`
Also update comments.

Update Purchaser/Customer related naming -> Rename of old API before adding in new API.

---

package.json
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin+Attribution.swift
src/ios/PurchasesPlugin+Users.swift
src/plugin/plugin.ts
www/plugin.d.ts
www/plugin.js

**Adds**
`INTRO_ELIGIBILITY_STATUS_NO_INTRO_OFFER_EXISTS` To `INTRO_ELIGIBILITY_STATUS`
`activeInCurrentEnvironment`, `activeInAnyEnvironment`, to `PurchasesEntitlementInfos`
**Renames**
`PurchasesProduct`->`PurchasesStoreProduct`
`PurchasesTransaction`->`PurchasesStoreTransaction`
**Replaces** 
`revenueCatId`, with `transactionIdentifier` in `PurchasesStoreTransaction`
`productId`, with `productIdentifier` in `PurchasesStoreTransaction`
**Removes**
`ATTRIBUTION_NETWORKS` from `Purchases`
`addAttributionData`, `createAlias`, `identify`, `reset`, `setAllowSharingStoreAccount` from `Purchases`

Phase 1 of update/add/remove api

---

package.json

I was testing this https://github.com/RevenueCat/cordova-plugin-purchases/issues/112#issuecomment-1183431151 and realized that we don't have the dependency in the package.json so it doesn't get automatically installed when installing the plugin via npm.

Adds cordova-annotated-plugin-android dependency to package.json

---

src/plugin/plugin.ts
www/plugin.d.ts

Adds:
- `PurchasesPromotionalOffer`
- `PurchasesIntroPrice`
- `PurchasesStoreProductDiscount`
Removes properties:
- `readonly intro_price_string: string | null;`
- `readonly intro_price_period: string | null;`
- `readonly intro_price_cycles: number | null;`
from `PurchasesStoreProduct`
Updates type of property in `PurchasesStoreProduct`:
`readonly intro_price: number | null;` to `readonly intro_price: PurchasesIntroPrice | null;`

Update data model for iOS RCv4, Android v5

---

examples/cordova-sample/MyApp/www/js/index.js
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin.swift
src/plugin/plugin.ts
tests/plugin.test.ts
tests/tests.js
www/plugin.d.ts
www/plugin.js

Brings our API back to the same naming as our current native releases.
Resolves [CSDK-187]
[CSDK-187]: https://revenuecats.atlassian.net/browse/CSDK-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Purchases.setup to Purchases.configure

---

CHANGELOG.md
package.json
plugin.xml
scripts/docs/index.html
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin.swift

- Updated `readonly intro_price: PurchasesIntroPrice | null;` to `readonly introPrice: PurchasesIntroPrice | null;`
- Updated `readonly price_string: string;` to `readonly priceString: string;`
- Updated `readonly currency_code: string;` to `readonly currencyCode: string;`
*See previous 3.0.0-rc.x notes for a complete log.*
- Bump`purchases-hybrid-common` to `4.0.0` 
[4.0.0 Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/tag/4.0.0)
- Bump `purchases-ios` to `4.9.1` 
[4.9.1 Changelog here](https://github.com/RevenueCat/purchases-ios/releases/4.9.1)

Preparing for version 3.0.0-rc.4

---

examples/cordova-sample/MyApp/www/js/index.js
plugin.xml
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin+Attribution.swift
src/plugin/plugin.ts
www/plugin.d.ts
www/plugin.js

- Updated Hybrid Common to `4.1.0`
- Adds new `enableAdServicesAttributionTokenCollection` method
- No-op on non-iOS platforms

Update Hybrid Common 4.1.0 and add AdServices

---

CHANGELOG.md
package.json
plugin.xml
scripts/docs/index.html
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin.swift

- Added attribution methods for CleverTap, Mixpanel, and Firebase.
`Purchases.setCleverTapID`, `Purchases.setMixpanelDistinctID`, and `Purchases.setFirebaseAppInstanceID`
*See previous 3.0.0-rc.x notes for a complete log.*
- Bump`purchases-hybrid-common` to `4.2.0`
[4.2.0 Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/tag/4.2.0)
- Bump `purchases-android` to `5.6.0`
[5.6.0 Changelog here](https://github.com/RevenueCat/purchases-android/releases/5.6.0)

Preparing for version 3.0.0-rc.8

---

examples/cordova-sample/MyApp/www/js/index.js

This fixes race conditions in the example app.
The issue is that the app assumes that configure isn't async, but it actually is (the signature is broken 🤦)
`configure` does actually output an event when it's done, so the quick fix is to just subscribe to that event. 
The real fix would be to fix the configure method, but that's a separate PR. 
This is the kind of error we were getting before, when calling a method right after calling configure:

fix: race conditions in example app

---

Gemfile.lock

After the automation in #182, it should have created a PR bumping the version to the next snapshot version but it failed: https://app.circleci.com/pipelines/github/RevenueCat/cordova-plugin-purchases/785/workflows/b7c08242-c961-4b06-bd61-81a75c68e1a6/jobs/1377 . Looks like in CircleCI machines, we are adding the `x86_64-linux` platform for some reason... which is causing git to be dirty and so it fails on the job. This PR just adds that platform to the lock file, done using: `bundle lock --add-platform x86_64-linux`.

Fix prepare_next_version job in CircleCI machines

---

examples/cordova-sample/MyApp/www/js/index.js
src/android/PurchasesPlugin.java

We were calling configure in the UI thread (main)
This is the thread where Cordova Java code runs. Note is in the `main` pool but it's not the main thread. 
We had `ExecutionThread.UI` as the thread configure should be running on. So this code in the annotation plugin was running on that JavaBridge thread:
```
Object[] mArgs = getMethodArgs(args, callbackContext);
Runnable runnable = this.createRunnable(mArgs, caller, callbackContext);
if (executionThread == ExecutionThread.WORKER) {
cordova.getThreadPool().execute(runnable);
} else if (executionThread == ExecutionThread.UI) {
cordova.getActivity().runOnUiThread(runnable);
} else {
runnable.run();
}
```
And calling `configure` in our plugin in the `main` thread in the `main` pool. Setting a breakpoint inside `configure` in phc shows this …

Configure should be called in the current thread and not in a UI thread

---

apiTester/offerings.ts
apiTester/purchases.ts
src/plugin/plugin.ts
www/plugin.d.ts

We are missing `getPromotionalOffer` and `purchaseDiscountedProduct` so this interface is useless
I added it to the SDK feature parity sheet

Removes PurchasesPromotionalOffer

---

.circleci/config.yml

This new version includes https://github.com/RevenueCat/sdks-circleci-orb/pull/7 which fixes the deployments

Update orb to fix deploys

---

.circleci/config.yml

Upgrading to Xcode 13.4 broke the integration tests because we were getting this error: `xcrun: error: unable to find utility "instruments", not a developer tool or in PATH`
In this PR I upgraded the CI to use the macos orb, which has some tools that help with mac machines.

Fix iOS Cordova paramedic tests

---

fastlane/Fastfile

`bump_version_update_changelog_create_pr` was missing the `automatic_release` parameter. We pass it as `true` from the `automatic_bump` lane, but forgot to pass it to `bump_version_update_changelog_create_pr`.
This was causing automatic bump PRs to not have the `[AUTOMATIC]` text in the title. For example https://github.com/RevenueCat/cordova-plugin-purchases/pull/213, whereas this other react-native-purchases PR has the correct title https://github.com/RevenueCat/react-native-purchases/pull/458

Adds missing parameter to bump_version_update_changelog_create_pr

---

.circleci/config.yml

Equivalent of https://github.com/RevenueCat/purchases-android/pull/644/files
Fixes two things:
- Makes sure integration tests pass before deploying anything
- Prevents integration tests from running also when the branch is tagged (after the hold job is approved), which was unnecessary

Makes hold job depend on integration tests

---

src/ios/PurchasesPlugin.swift

Fixes https://github.com/RevenueCat/cordova-plugin-purchases/issues/181
Tested it on a new Ionic + Capacitor project and this fixed the issue

Fix CDVPlugin class CDVPurchasesPlugin (pluginName: purchasesplugin) does not exist bug

---

apiTester/purchases.ts
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin.swift
src/plugin/plugin.ts

Fixes [CSDK-608].
Depends on https://github.com/RevenueCat/purchases-android/pull/753 and https://github.com/RevenueCat/purchases-hybrid-common/pull/301
[CSDK-608]: https://revenuecats.atlassian.net/browse/CSDK-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added `Purchases.setLogLevel`

---

src/plugin/plugin.ts

addresses sdk-2885. Deprecates `usesStoreKit2IfAvailable` configuration parameter.

Deprecate `usesStoreKit2IfAvailable` configuration parameter

---

.circleci/config.yml

- Fixes version in CI to Cordova 11 since Cordova Paramedic can't use Cordova 12 (same changes as in https://github.com/RevenueCat/cordova-plugin-purchases/blob/bc5-support/.circleci/config.yml#L46)
- Updated xcode version

Fix iOS integration tests

---

apiTester/offerings.ts
examples/cordova-sample/MyApp/www/js/index.js
plugin.xml
src/plugin/plugin.ts

Add `metadata` to `PurchasesOffering`
- Bumped Android, iOS, and macOS to hybrid common `5.0.0-rc.1`
- Added `metadata: Map<string, any>` to `PurchasesOffering`
- Updated API tester
**DID NOT** add a `getMetadataString(String key, String defaultValue)` because TypeScript interfaces 😔

Add metadata to offering

---

src/ios/PurchasesPlugin+Purchasing.swift

Addresses https://github.com/RevenueCat/purchases-ios/issues/2356#issuecomment-1623783559
This method [is not actually available on Catalyst](https://github.com/RevenueCat/purchases-hybrid-common/blob/2c45895568dc3dbacfa2e3c401acd2b8ed322b7e/ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift#L133) (see https://github.com/RevenueCat/purchases-hybrid-common/pull/197).

`presentCodeRedemptionSheet`: disabled on Catalyst

---

apiTester/offerings.ts
src/plugin/plugin.ts

As reported in https://github.com/RevenueCat/react-native-purchases/issues/700. The typescript interface has specified the wrong type for metadata. We're not using typescript Maps, but simple objects for metadata. This should be an object of key strings and unknown values.
Cordova equivalent of https://github.com/RevenueCat/react-native-purchases/pull/702

Use correct type for offering metadata

---

src/plugin/plugin.ts

Added a small example of how to access offering metadata values to the documentation.

Update offering metadata documentation with a usage example

---

.circleci/config.yml

Intel machines are deprecated by CircleCI. This updates our machines to use the M1 machines

Update to use M1 CircleCI machines

---

.circleci/config.yml
package.json

This reverts back to use M1 CI machines for iOS tests. In the meantime, I updated to the latest paramedic commit and had to select the simulator (it didn't work automatically for some reason). This means we will need to update it from time to time

Fix cordova ios integration tests

---

.circleci/config.yml
.sdkmanrc

We were using a super old version of the android orb and executor. This updates them to the latest.

Update android executor

---

apiTester/purchases.ts
examples/cordova-sample/MyApp/RevenueCatTest.storekit
examples/cordova-sample/MyApp/www/index.html
examples/cordova-sample/MyApp/www/js/index.js
src/android/PurchasesPlugin.java
src/ios/PurchasesPlugin+Purchasing.swift
src/plugin/plugin.ts

This PR exposes four new functions to allow developers to fetch & redeem win-back offers that a subscriber is eligible for in their custom paywalls. These functions only function on iOS 18.0+ and require StoreKit 2 to be used.
```typescript
public static async getEligibleWinBackOffersForProduct(
product: PurchasesStoreProduct,
callback: (winBackOffers: PurchasesWinBackOffer[]) => void,
errorCallback: (error: PurchasesError) => void
)
public static async getEligibleWinBackOffersForPackage(
aPackage: PurchasesPackage,
callback: (winBackOffers: PurchasesWinBackOffer[]) => void,
errorCallback: (error: PurchasesError) => void
)
```
```typescript
public static async purchaseProductWithWinBackOffer(
product: PurchasesStoreProduct,
winBackOffer: PurchasesWinBackOffer,
callback: …
```

Support Fetching and Redeeming Win-Back Offers on Custom Paywall

---

src/plugin/plugin.ts

Documents the PREPAID `periodType` value, introduced in https://github.com/RevenueCat/purchases-hybrid-common/pull/1054. Since the value is coming from PurchasesHybridCommon, this should be all we need to do to support the new periodType case in Cordova.

Document PREPAID periodType

---

.circleci/config.yml

This fixes an issue that was making it fail when trying to update PHC due to not finding ruby 3.2.0. This was introduced in #718

Change ruby version in `update-hybrid-common-versions` job

---

.circleci/config.yml
Gemfile.lock
fastlane/Fastfile

This PR makes the changes needed for the next release of v10.
* Bump [fastlane-plugin-revenuecat_internal](https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal) from `05ef095 ` to `1593f78`. See full diff in <a href="https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/compare/05ef0952ecb3b92398a0185a3f74019abd0c1d95...1593f78d0b9b24b48238337666183e3ba82f848e">compare view</a>.
* Pass current version in automatic bump.
* [CI] Only `build` pipeline action can trigger `on-release-branch` workflow.

[v6] Prepare for next release

---

.circleci/config.yml
Gemfile.lock
fastlane/Fastfile
fastlane/README.md

Follow-up of #740
Bumps [fastlane-plugin-revenuecat_internal](https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal) from `1593f78` to `a8770fd`.
See full diff in <a href="https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/compare/7d97553e9c5baabcd18286f03d8034797a27dd64...1593f78d0b9b24b48238337666183e3ba82f848e">compare view</a></li>
This version of fastlane-plugin-revenuecat_internal includes the new `insert_changelog_latest_in_main_if_needed` action that creates a PR into `main` to insert the changelog of a new release of a previous major into `main`'s changelog.
This PR also implements that new `insert_changelog_latest_in_main_if_needed`

[v6] Update fastlane plugin
